export const RouteList = {
  Home: `/`,
  Login: `/login`,
  ChangePassword: `/change-password`,

  Dashboard: `/dashboard`,
  Setting: `/Setting`,
  Category: "/category",
  Course: "/course",
  Blog: "/blog",
  BlogDescription: "/blog-description",
  LatestNews: "/latest-news",
  LatestNewsDescription: "/latest-news-description",
  Chats: "/chats",
  AboutUs: `/about-us`,
  PrivacyPolicy: `/privacy-policy`,
  TermsAndConditions: `/terms-and-conditions`,
  ErrorPages: `/error-pages`,
  Lecture: "/lecture",
};
